name: Pull Request Workflow

on:  pull_request

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Unit Tests
        run: ./gradlew test

  check:
    name: Lint, Ktlint and Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Android Linter
        run: ./gradlew lint

      - name: Run Ktlint
        run: ./gradlew ktlint

      - name: Run Detekt
        run: ./gradlew detekt
